# Generated by Django 2.1.2 on 2018-10-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to=settings.AUTH_USER_MODEL),
        ),
    ]
