# Generated by Django 2.1.2 on 2018-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon_url',
            field=models.CharField(default='/images/languages/default.png', max_length=256),
        ),
    ]
