# Generated by Django 2.1.2 on 2018-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20181124_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo_filename',
            field=models.CharField(default='default.png', max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_filename',
            field=models.CharField(default='default.png', max_length=16),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo_filename',
            field=models.CharField(default='default.png', max_length=16),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon_filename',
            field=models.CharField(default='default.png', max_length=16),
        ),
    ]
