# Generated by Django 2.1.2 on 2018-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20181026_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='filmactor',
            options={'ordering': ('actor_id',)},
        ),
        migrations.AlterModelOptions(
            name='filmcategory',
            options={'ordering': ('category_id',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subtitles',
            options={'ordering': ('film_id',)},
        ),
        migrations.AlterModelOptions(
            name='userfilm',
            options={'ordering': ('user_id',)},
        ),
        migrations.AddField(
            model_name='language',
            name='icon_name',
            field=models.CharField(default='icon.png', max_length=16),
            preserve_default=False,
        ),
    ]
