# Generated by Django 2.1.2 on 2018-11-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20181124_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='films', to='films.Actor'),
        ),
    ]
