# Generated by Django 2.1.2 on 2018-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20181112_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='language_id',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='films', to='films.Language'),
        ),
    ]
