# Generated by Django 2.1.2 on 2018-11-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20181112_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.Category'),
        ),
        migrations.AlterField(
            model_name='filmcategory',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='films.Film'),
        ),
    ]
