# Generated by Django 2.1.2 on 2018-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20181112_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='filmcategory',
            name='film_id',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='films.Category'),
        ),
        migrations.DeleteModel(
            name='FilmCategory',
        ),
    ]
